# GitHub Actions 파일 (roomcatcher.yml)
name: Deploy Prochord
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: List files in current directory
        run: ls -la
      # 3. Docker 이미지 빌드 및 테스트 실행 후 push
      - name: Build Docker image for testing
        run: docker buildx build --platform linux/amd64 --load --tag 5hseok/prochord_server:0.0.1 -f ./Dockerfile .

      #      - name: Run tests in Docker container
      #        run: docker run -e CI=true 5hseok/prochord_server:0.0.1 ./gradlew test

      - name: Push Docker image to Docker Hub
        run: docker push 5hseok/prochord_server:0.0.1

      # 5. EC2에서 deploy.sh 실행
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /app
            docker-compose down
            docker-compose pull
            docker-compose up -d